Upgrade v3 (#6)
* Deps update: initial commit

* Update Phoenix 1.4 -> 1.5, Elixir 1.10.2 -> 1.10.3

* Pending txs per address API endpoint

* Fix coin balance history page if no balance changes

* Add CHANGELOG entry

* Release 3.1.3

* Display and store revert reason on demand

* Update test

* Add tests

* Add unit tests

* Fix contract compilation tests for old versions of compiler: change compiler version since nightly versions of some older versions were removed

* Add CHANGELOG entry

* Disable Pending transactions supervisor

* trace_block for BESU

* Proxy contracts: decoding using implementation ABI

* Check if implementation is verified

* Decode log in proxy contracts

* Add tests

* Fix several tests

* Blockcout 3.2.0

* Read proxy

* Proxy reader: handle function with params

* Write contracts: a new tab with the list of write methods

* Check if Metamask is authorized, increase container width to comply with increased max possible number of tabs

* A modal window with pending tx hash

* Write contract feature: support payble methods

* Change button name from query to write

* Write proxy contract feature

* Fix for definnition of contract type: proxy/regular

* Write proxy: remove redundant variable declaration: contract_type

* Fix for acocunts page with token-bridge supply and inexistent bridge contracts

* Add Changelog entry

* Fix for verification of contracts from genesis block

* Add CHANGELOG entry

* Import accounts from Geth geenesis

* Update CHANGELOG entry

* Add tests

* Exclude constructors from Write contract page

* Fix error on token\'s read contract tab

* Add tests

* Display implementation address at read/write proxy tabs

* EIP-1967 support

* Blockscout 3.3.0

* eip1967 update: handle different size response from eth_getStorageAt for implementation address

* Fix permanent fetching tokens and unavailable navbar menu when read/write proxy tab is active

* Return correct status to verify api if conntract verified, remove Kovan from the list of default chains

* Besu: Add revertReason key

* Apps menu item

* Add env vars to Docker setup

* Transaction page: decoding logs from called contracts

* Add HCANGELOG entry

* Address logs decoding fix

* Improve decode log/method view

* Add CHANGELOG entry

* Refine decoding view of contract method, log on transaction page, refactoring

* Handle empty block author reward

* Fix non-interactive navbar at not found page

* Add CHANGELOG entry

* Raw trace copy button

* Add CHANGELOG entry

* Update npm deps

* Update node version in Circle CI config

* Show compilation error at conntract verification

* Connect to Metamask button

* Add top marging for implementation address container

* Fix verification with experimental features enabled

* Add CHANGELOG entry

* Improve get mined blocks query performance: remove grouping by number, timestamp

* Add CHANGELOG entry

* GraphQL Absinthe related packages update up to stable versions

* Add CHANGELOG entry

* Process GraphQL internal server error for address -> transactions query without first/last params

* Update Elixir version: 1.10.2 -> 1.10.3

* Add CHANGELOG entry

* Update deps

* Fix read contract bytes array type

* Fix view for read contract

* GraphQL: fix innternal server error at request of internal transactions at address

* Add CHANGELOG entry

* Remove line for debugging

* Fix tests

* Process TypeError: Cannot read property el of undefined

* Update CHANGELOG entry

* Github Actions CI config

* Add umbrella apps tests

* Update

* Disable flaky tests

* coveralls

* Decrease minimum coverage value

* Update CI status badge

* Update coveralls push

* Disable flaky test

* Fetch current token balances fix

* Temporarily remove coveralls step in CI

* coveralls

* pubsub for new token transfers

* Temp last

* Fix revert reason detection

* Remove flaky tests

* Finalize pubsub for token transfers

* Blockscout v3.3.1

* Fix navbar menu at block not found page

* Search in one click

* Adding Top tokens page

* Add Paging_params for Token

* Finally fix pagination at top tokens page

* Remove unused var

* Enable navbar at top tokens page

* Return page_size 50

* Fix notifier query for live update of token transfers

* Bridged tokens

* Remove caching of mix.exs from GA

* Fix tests

* Finalize bridged tokens

* Fix query for bridged token feature

* set default value for get_base_token_explorer_link function

* Make wobserver optional

* Mix format

* Fix foreign chaind detection

* Finalize bridged tokens

* Improve search: allow search with space

* Unlimited number of tokens in search results

* Searching results: improve ordering: token holders desc, name asc

* Fix for the contract verifiaction for solc 0.5 family with experimental features enabled

* Add CHANGELOG entry

* Fix dialyzer test

* Fix coin supply api

* Easy verification from verified twins

* Fix tests

* Fix one more test

* Fix contract funnction method detection

* Add CHANGELOG entry

* Fix tests

* Hide address tabs if no items

* Rwmove internal transactions tab hiding

* Fix gettext

* Style fixes: xDai links, search hover color, "token is bridged" text, handle token name at token page if name/symbol is empty

* Fix gettext

* Contract reader fix

* ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT -> ETHEREUM_JSONRPC_TRANSPORT

* xDai: do not apply link style for buttons

* Gas price at the main page

* Tertiary color for gas price icon

* Update Docker config

* 3.3.2 release

* Fix for invisible validator address at block page

* Modified Blockscout repo

* Color & logo update

* moved image to right location

* UI changes (#5)

* Update _neutral_variables.scss

* Update _neutral_variables.scss

* Update config.exs

* Update config.exs

* Update config.exs

* Update default.po

* Update _topnav.html.eex

* Update _nav_tabs.scss

* Update _footer.html.eex

* Update _footer.html.eex

* Update default.pot

* Update default.pot

* Update default.po

* favicon

* Create favicon.ico

* Merge branch 'poanetwork-master' (#6)

* add default query to graphiql-playground

* pass default query to GraphiQL interface

* add missing alias

* fix credo

* do not try to convert nils in logs

* mix format

* do not create contracts on failed parent transactions

* exclude test from parity

* remove output field from internal transaction

* add indexes for block_reward query

* check if to_address_hash is contract address to fetch internal transactions

* pass json_rpc_arguments to Chain.contract_address?

* fetch address balances in code fetcher

* fix dialyzer

* feat: show an approximation of transaction time

* fix: add coin_balance_status to address_validations

* fix: resolve lodash security alert

* fix: configure BLOCKSCOUT_VERSION in a standard way

* after running "mix gettext.extract --merge"

* after running "mix gettext.extract --merge" inside "./apps/block_scout_web"

* added fuse logo

* remove apps/*/priv/static from ignore

* another attempt

* Revert "added fuse logo"

This reverts commit 3c4bc8689082dab4ad9352c1f66062d037273f94.

* fuse network (#1)

* v2.0.1-beta modified to fuse

* prepare for deployment

* make docker work

* docker run command

* replaced price graph with images

* removed "warnings-as-errors" on compile

* updated footer

* Fuse explorer UI update (#2)

* frontend work and updated translations

* added rxjs and web3 libs, added util functions, added fuse.io to connect-src

* added other metrics

* remove hardcoded urls

* added changes to docker

* fixed typos

* added svg icons, added circle-progress, added more css changes

* fix alignment

* changed cycleEnd polling interval and changed algo for calc cycle length

* added new_cycle_module, added new util functions, added new ENV param VALIDAORS_INFO_URL, added show more link

* added margin to current cycle blocks value

* added css fix for mobile card

* added new classes to html to make page responsive on tablets

* display Fuse instead of Ether

* initial commit

* added upgrade changes

* added ui changes

* added final changes

* added fixes

* fix makefile var name for params

* fix for word spacing in transactions

* added new logo

* added footer-logo fix and make container start as daemon

Co-authored-by: Victor Baranov <baranov.viktor.27@gmail.com>
Co-authored-by: Arsenii Petrovich <arsenii.petrovich@altoros.com>
Co-authored-by: Marksmargon <mark@colu.co>
Co-authored-by: Lior Rabin <lior@colu.com>
Co-authored-by: Lior Rabin <lior9586@gmail.com>
Co-authored-by: Lior Rabin <lior@fusenet.io>
Co-authored-by: Lior Rabin <lior@fuse.io>